export enum sagaType {
  GET_PROFILE_PAGE = 'SAGA/PROFILE_PAGE',
  UPDATE_PROFILE_STATUS = 'SAGA/UPDATE_PROFILE_STATUS',
  FOLLOW_USER = 'SAGA/FOLLOW_USER',
  UNFOLLOW_USER = 'SAGA/UNFOLLOW_USER',
  UPLOAD_USER_PHOTO = 'SAGA/UPLOAD_USER_PHOTO',
  UPDATE_PROFILE = 'SAGA/UPDATE_PROFILE',
}
