export enum sagaType {
  GET_PROFILE_PAGE = 'SAGA/PROFILE_PAGE',
  UPDATE_PROFILE_STATUS = 'SAGA/UPDATE_PROFILE_STATUS',
  UPLOAD_USER_PHOTO = 'SAGA/UPLOAD_USER_PHOTO',
  UPDATE_PROFILE = 'SAGA/UPDATE_PROFILE',
}
