export enum profileActionType {
  ADD_POST = 'profile/ADD_POST',
  DELETE_POST = 'profile/DELETE_POST',
  SET_USER_PROFILE = 'profile/SET_USER_PROFILE',
  SET_PROFILE_STATUS = 'profile/SET_PROFILE_STATUS',
  SET_FRIENDSHIP = 'profile/SET_FRIENDSHIP',
  UPLOAD_USER_PHOTO_SUCCESS = 'profile/UPLOAD_USER_PHOTO_SUCCESS',
  UPDATE_PROFILE_SUCCESS = 'profile/UPDATE_PROFILE_SUCCESS',
  SET_IS_FETCHING = 'profile/SET_IS_FETCHING',
}
