export enum usersActionType {
  FOLLOW_SUCCESS = 'users/FOLLOW_SUCCESS',
  UNFOLLOW_SUCCESS = 'users/UNFOLLOW_SUCCESS',
  SET_USERS = 'users/SET_USERS',
  SET_CURRENT_PAGE = 'users/SET_CURRENT_PAGE',
  SET_TOTAL_MEMBERS = 'users/SET_TOTAL_MEMBERS',
  TOGGLE_IS_FETCHING = 'users/TOGGLE_IS_FETCHING',
  TOGGLE_PRESSING_IN_PROGRESS = 'users/TOGGLE_PRESSING_IN_PROGRESS',
  SET_USERS_FILTER = 'users/SET_USERS_FILTER',
  SET_FOLLOWINGS = 'users/SET_FOLLOWINGS',
  SET_FOLLOWINGS_COUNT = 'users/SET_FOLLOWINGS_COUNT',
}
